"""
loader.py
---------

Stage 6 of the pipeline: Python -> SQL Server ETL.

Dimensions are loaded before fact_sales because fact_sales references
the dimension tables through foreign keys.

All loads are incremental: rows whose key already exists in the target
table are skipped.
"""

import logging

import pandas as pd
from sqlalchemy.engine import Engine

from src.database import insert_new_rows


logger = logging.getLogger(__name__)


# Column order expected by dbo.fact_sales.
FACT_COLUMNS = [
    "Order_ID",
    "Order_Date",
    "Customer_ID",
    "Product_ID",
    "Region_Key",
    "Payment_Method",
    "Sales",
    "Quantity",
    "Discount",
    "Cost",
    "Profit",
    "Profit_Margin",
    "Gross_Revenue",
    "Is_Outlier",
    "Source_File",
    "Ingestion_Timestamp",
]


def _load_dim_customer(df: pd.DataFrame, engine: Engine) -> int:
    """Load new customers incrementally."""

    dim = (
        df[
            [
                "Customer_ID",
                "Customer_Name",
            ]
        ]
        .drop_duplicates(subset=["Customer_ID"])
        .reset_index(drop=True)
    )

    return insert_new_rows(
        engine,
        dim,
        "dim_customer",
        "Customer_ID",
    )


def _load_dim_product(df: pd.DataFrame, engine: Engine) -> int:
    """Load new products incrementally."""

    dim = (
        df[
            [
                "Product_ID",
                "Product_Name",
                "Category",
                "Sub_Category",
            ]
        ]
        .drop_duplicates(subset=["Product_ID"])
        .reset_index(drop=True)
    )

    return insert_new_rows(
        engine,
        dim,
        "dim_product",
        "Product_ID",
    )


def _load_dim_region_and_get_keys(
    df: pd.DataFrame,
    engine: Engine,
) -> tuple[pd.DataFrame, int]:
    """
    Load new Region/State/City combinations.

    Region_Key is generated by SQL Server as an IDENTITY value, so the
    complete mapping is read back from the database afterward.
    """

    combos = (
        df[
            [
                "Region",
                "State",
                "City",
            ]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    existing = pd.read_sql(
        "SELECT Region, [State], City FROM dim_region",
        con=engine,
    )

    existing_set = set(
        existing.itertuples(
            index=False,
            name=None,
        )
    )

    is_new = combos.apply(
        lambda row: (
            row["Region"],
            row["State"],
            row["City"],
        )
        not in existing_set,
        axis=1,
    )

    new_combos = combos[is_new]

    inserted = 0

    if not new_combos.empty:
        new_combos.to_sql(
            name="dim_region",
            con=engine,
            if_exists="append",
            index=False,
            chunksize=100,
            method=None,
        )

        inserted = len(new_combos)

        logger.info(
            "Inserted %d new region combination(s) into 'dim_region'.",
            inserted,
        )

    mapping = pd.read_sql(
        "SELECT Region_Key, Region, [State], City FROM dim_region",
        con=engine,
    )

    return mapping, inserted


def _validate_fact_sales(fact_df: pd.DataFrame) -> pd.DataFrame:
    """
    Remove fact rows that violate the SQL Server Sales constraint.

    dbo.fact_sales requires Sales to be greater than zero.
    """

    sales_numeric = pd.to_numeric(
        fact_df["Sales"],
        errors="coerce",
    )

    invalid_sales = (
        sales_numeric.isna()
        | (sales_numeric <= 0)
    )

    invalid_count = int(invalid_sales.sum())

    if invalid_count > 0:
        logger.error(
            "%d row(s) have invalid Sales values and will be excluded "
            "from the fact_sales load.",
            invalid_count,
        )

        logger.error(
            "Invalid Sales examples:\n%s",
            fact_df.loc[
                invalid_sales,
                [
                    "Order_ID",
                    "Sales",
                ],
            ].head(10),
        )

        fact_df = fact_df.loc[~invalid_sales].copy()

    fact_df["Sales"] = sales_numeric.loc[fact_df.index]

    return fact_df


def load_to_db(
    df: pd.DataFrame,
    engine: Engine,
) -> dict:
    """
    Load transformed data into the SQL Server star schema.

    Dimensions are loaded first. Fact rows are then assigned a
    Region_Key and inserted incrementally using Order_ID.

    Returns:
        Dictionary containing the number of inserted rows per table.
    """

    if df.empty:
        logger.warning(
            "load_to_db called with an empty DataFrame - nothing to load."
        )

        return {
            "dim_customer": 0,
            "dim_product": 0,
            "dim_region": 0,
            "fact_sales": 0,
        }

    summary = {
        "dim_customer": _load_dim_customer(df, engine),
        "dim_product": _load_dim_product(df, engine),
    }

    region_map, region_inserted = _load_dim_region_and_get_keys(
        df,
        engine,
    )

    summary["dim_region"] = region_inserted

    # Attach Region_Key to every fact row.
    fact_df = df.merge(
        region_map,
        on=[
            "Region",
            "State",
            "City",
        ],
        how="left",
    )

    # Remove rows that could not be mapped to a region.
    unmapped = fact_df["Region_Key"].isna()

    if unmapped.any():
        logger.error(
            "%d row(s) failed to map to a Region_Key - dropping them "
            "from this load.",
            unmapped.sum(),
        )

        fact_df = fact_df.loc[~unmapped].copy()

    # Rename transformed columns to match SQL Server column names.
    fact_df = fact_df.rename(
        columns={
            "is_outlier": "Is_Outlier",
            "source_file": "Source_File",
            "ingestion_timestamp": "Ingestion_Timestamp",
        }
    )

    # Convert date columns to datetime values.
    fact_df["Order_Date"] = pd.to_datetime(
        fact_df["Order_Date"],
        errors="coerce",
    )

    fact_df["Ingestion_Timestamp"] = pd.to_datetime(
        fact_df["Ingestion_Timestamp"],
        errors="coerce",
        utc=True,
    ).dt.tz_localize(None)

    # Convert nullable datetime values to Python None.
    fact_df["Order_Date"] = fact_df["Order_Date"].where(
        fact_df["Order_Date"].notna(),
        None,
    )

    fact_df["Ingestion_Timestamp"] = fact_df[
        "Ingestion_Timestamp"
    ].where(
        fact_df["Ingestion_Timestamp"].notna(),
        None,
    )

    # Convert text columns to ordinary Python objects for pyodbc.
    text_columns = [
        "Order_ID",
        "Customer_ID",
        "Product_ID",
        "Payment_Method",
        "Source_File",
    ]

    for column in text_columns:
        if column in fact_df.columns:
            fact_df[column] = fact_df[column].astype(object)

            fact_df[column] = fact_df[column].where(
                fact_df[column].notna(),
                None,
            )

    # Region_Key is generated by SQL Server and must be an integer.
    fact_df["Region_Key"] = fact_df["Region_Key"].astype(int)

    # Keep only the columns required by fact_sales, in the correct order.
    fact_df = fact_df[FACT_COLUMNS].copy()

    # Validate Sales against dbo.fact_sales constraint:
    # CHECK (Sales > 0)
    fact_df = _validate_fact_sales(fact_df)

    if fact_df.empty:
        logger.warning(
            "No valid fact_sales rows remain after validation."
        )

        summary["fact_sales"] = 0

        logger.info(
            "Load summary: %s",
            summary,
        )

        return summary

    # Ensure numeric columns contain numeric values.
    numeric_columns = [
        "Sales",
        "Quantity",
        "Discount",
        "Cost",
        "Profit",
        "Profit_Margin",
        "Gross_Revenue",
    ]

    for column in numeric_columns:
        fact_df[column] = pd.to_numeric(
            fact_df[column],
            errors="coerce",
        )

    # Diagnostic logging before insertion.
    logger.info(
        "Fact dataframe dtypes:\n%s",
        fact_df.dtypes,
    )

    if fact_df["Ingestion_Timestamp"].notna().any():
        timestamp_sample = (
            fact_df["Ingestion_Timestamp"]
            .dropna()
            .iloc[0]
        )

        logger.info(
            "Ingestion_Timestamp Python type: %s",
            type(timestamp_sample).__name__,
        )

        logger.info(
            "Ingestion_Timestamp sample: %r",
            timestamp_sample,
        )

    logger.info(
        "Fact rows ready for insertion: %d",
        len(fact_df),
    )

    summary["fact_sales"] = insert_new_rows(
        engine,
        fact_df,
        "fact_sales",
        "Order_ID",
    )

    logger.info(
        "Load summary: %s",
        summary,
    )

    return summary